apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: xh-test
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: tcp
  selector:
    app: elasticsearch

