apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: xh-test
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch-service
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms128m -Xmx128m"






