apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: xh-test
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: tcp
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport-service
  namespace: xh-test
spec:
  type: NodePort
  ports:
    - port: 9200
      name: http
      targetPort: 9200
      nodePort: 31200
    - port: 9300
      name: tcp
      targetPort: 9300
      nodePort: 31300
  selector:
    app: elasticsearch

