apiVersion: v1
kind: Pod
metadata:
  name: stack-app
  labels:
    app: stack-app
spec:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  containers:
    - name: stack-app
      image: "echisan/app:v1-exception"
      ports:
        - containerPort: 8888
      env:
        - name: aliyun_logs_stack-app
          value: "stdout"
        - name: aliyun_logs_stack-app-log-file
          value: "/logs/*.log"
      volumeMounts:
        - mountPath: logs
          name: test-app-log
  volumes:
    - name: test-app-log
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: stack-app-service
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 31083
  selector:
    app: stack-app
