apiVersion: v1
kind: Pod
metadata:
  name: test-app
spec:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  containers:
    - name: test-app
      image: "echisan/elk-app:v1"
      env:
        - name: aliyun_logs_testapp
          value: "stdout"
        - name: aliyun_logs_testapplogfile
          value: "/logs/*.log"
        - name: aliyun_logs_testapplogfile_format
          value: "json"
      volumeMounts:
        - mountPath: logs
          name: test-app-log
  volumes:
    - name: test-app-log
      emptyDir: {}
