apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-cluster-data
spec:
  serviceName: es-cluster-data
  template:
    metadata:
      name: es-cluster-data
      labels:
        app: es-cluster-data
        role: master
    spec:
      containers:
        - name: es-data
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: network.host
              value: "_site_"
            - name: node.name
              value: "${HOSTNAME}"
            - name: discovery.zen.ping.unicast.hosts
              value: "es-cluster"
            - name: discovery.zen.minimum_master_nodes
              value: "2"
            - name: cluster.name
              value: "test-cluster"
            - name: node.master
              value: "false"
            - name: node.data
              value: "true"
            - name: node.ingest
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms128m -Xmx128m"
          volumeMounts:
            - name: es-cluster-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-cluster-storage
          emptyDir: {}
