apiVersion: v1
kind: Service
metadata:
  name: es-cluster-nodeport
spec:
  type: NodePort
  ports:
    - port: 9200
      name: http
      targetPort: 9200
      nodePort: 31200
    - port: 9300
      name: tcp
      targetPort: 9300
      nodePort: 31300
  selector:
    app: es-cluster
