apiVersion: v1
kind: Service
metadata:
  name: es-cluster-svc
spec:
  clusterIP: None # headless
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: tcp
  selector:
    app: es-cluster
