apiVersion: v1
kind: Service
metadata:
  name: kb-single-svc
spec:
  type: NodePort
  ports:
    - port: 5601
      name: http
      targetPort: 5601
      nodePort: 32601
  selector:
    app: kb-single
