apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-single
  labels:
    app: es-single
spec:
  selector:
    matchLabels:
      app: es-single
  template:
    metadata:
      name: es-single
      labels:
        app: es-single
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh","-c","chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-single-data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl","-w","vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh","-c","ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: es-single-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-single-data
          hostPath:
            path: /Users/echisan/volumes/elasticsearch2
---
apiVersion: v1
kind: Service
metadata:
  name: es-single
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: tcp
  selector:
    app: es-single
---
apiVersion: v1
kind: Service
metadata:
  name: es-single-nodeport
spec:
  type: NodePort
  ports:
    - port: 9200
      name: http
      targetPort: 9200
      nodePort: 31200
    - port: 9300
      name: tcp
      targetPort: 9300
      nodePort: 31300
  selector:
    app: es-single

