apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
  labels:
    app: elk-filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    output.elasticsearch:
      hosts: ["es-single:9200"]
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elk-filebeat
  namespace: default
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: elk-filebeat
      labels:
        app: elk-filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: filebeat
          image: store/elastic/filebeat:7.2.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          volumeMounts:
            - name: shared-data
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: shared-data
              mountPath: /var/log/containers
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: elk-app
          image: echisan/elk-app:v1
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /logs/
              name: shared-data
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  namespace: filebeat
subjects:
  - kind: ServiceAccount
    namespace: default
    name: filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
  verbs:
    - get
    - watch
    - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: default
  labels:
    app: elk-filebeat
---
apiVersion: v1
kind: Service
metadata:
  name: elk-app-service
  labels:
    app: elk-app-service
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: elk-app-service
  selector:
    app: elk-app-service
---
apiVersion: v1
kind: Service
metadata:
  name: elk-app-nodeport
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
      name: http
  selector:
    app: elk-app-service
