apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logstash
  namespace: xh-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logstash
subjects:
  - kind: ServiceAccount
    name: logstash
    namespace: xh-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logstash
  namespace: xh-test
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs:
      - get
