apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: xh-test
  labels:
    app: logging
    component: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}"}
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch-service:9200"]
        manage_template => false
        index => "%{[index]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
    }

  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-service:9200" ]

