apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: xh-test
spec:
  ports:
    - port: 9600
      targetPort: 9600
      name: logstash
      protocol: TCP
    - port: 5044
      targetPort: 5044
      name: filebeat
      protocol: TCP
  selector:
    app: logstash