apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
    app: filebeat-config
data:
  filebeat.yml: |
    processors:
      - add_cloud_metadata:
    filebeat.modules:
    - module: system
    filebeat.inputs:
    - type: log
      paths:
       # - /var/log/containers/*.log
        - /var/log/app/*.log
      symlinks: true
    output.elasticsearch:
      hosts: ['es-single:9200']
    logging.level: info
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      name: filebeat
      labels:
        app: filebeat
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: store/elastic/filebeat:7.2.0
          name: filebeat
          args: [
            "-c", "/home/filebeat-config/filebeat.yml",
            "-e",
          ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: filebeat-storage
              mountPath: /var/log/containers
            - name: varlogpods
              mountPath: /var/log/pods
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            - name: "filebeat-volume"
              mountPath: "/home/filebeat-config"
            - name: app-logs
              mountPath: /var/log/app
        - image: echisan/elk-app:v1
          name: elk-app
          volumeMounts:
            - name: app-logs
              mountPath: logs/
      volumes:
        - name: filebeat-storage
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: filebeat-volume
          configMap:
            name: filebeat-config
        - name: app-logs
          emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: default
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: default
  labels:
    k8s-app: filebeat
---
apiVersion: v1
kind: Service
metadata:
  name: elk-app-service
  labels:
    app: elk-app-service
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: elk-app-service
  selector:
    app: filebeat
---
apiVersion: v1
kind: Service
metadata:
  name: elk-app-nodeport
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
      name: http
  selector:
    app: elk-app-service
